
# name:   readme.org
# author: nbehrnd@yahoo.com
# date:   2019-12-17 (YYYY-MM-DD)
# edit:   [2022-11-10 Thu]

#+OPTIONS:  toc:nil

* Background

  Depending on the pdf creator/engine used, a =.pdf= file may include
  content irrelevant for reading by a human.  An example is the
  inclusion of complete sets of fonts though only a few glyphs are (or
  only one is) used on the "electronic paper".  To print the =.pdf=
  with =ghostscript= again into a =.pdf= may reduce the file size.

  By far, this bash script /does not/ claim to be the first one
  collecting bits and bolts to address the issue.  It rather serves as
  an aide-memoire of finds encountered earlier, and to moderate
  =ghostscript= in Linux accordingly.  Within reason, the snippets
  were joined as provided; thus, the credit belongs to those already
  in the field.
  
* Intended Use

  + The most comfortable use is to 1) provide the bash script the
    executable bit (=chmod +x pdf_reprint.sh=), and 2) to set an alias
    in your =.bashrc= file.  Then, you have its functionality
    described below all across your system.

  + Else, to reprint the =.pdf= while retaining the color, run either
    one of the following commands
    
    #+begin_src shell
      bash ./pdf_rewrite.sh --reprint input.pdf
      bash ./pdf_rewrite.sh -r input.pdf
      bash ./pdf_rewrite.sh --colour input.pdf
      bash ./pdf_rewrite.sh --color input.pdf
      bash ./pdf_rewrite.sh -c input.pdf
    #+end_src      

    which attempt /to replace/ the original file =input.pdf= by a new
    version of smaller file size.  In any case, there will be a short
    note if the attempt was successful; and if so, how much percent
    the new version is smaller, than the original.  Though you may
    process the file multiple times with this method, savings in file
    size often quickly converge to be insignificant in comparison to
    the remaining file size.

    The credit for the underlying approach and implementation belongs
    to Evan Langlois.[fn:1]

  + Often, an additional reduction of file size may be obtained by
    reprinting the =.pdf= in gray-scale only.  Either one of the
    following commands to the script is equivalent

    #+begin_src shell
      bash ./pdf_rewrite.sh --gray input.pdf
      bash ./pdf_rewrite.sh --grey input.pdf
      bash ./pdf_rewrite.sh -g input.pdf
    #+end_src
    
    to replace file =input.pdf= by its rewritten form.  The credit for
    this approach belongs to user =slm= on the Unix
    stackexchange.[fn:2]

  Note, this script's primary aim is to obtain a file of small file
  size, e.g., as an attachment of an email while retaining the text
  easy to read and -- if present -- to retain a text layer searchable.
  Especially the reprint in half-tones however may render
  illustrations less intelligible.  It is up to the creators of
  figures to use easy discernible markers in diagrams, and to use
  color scales suitable for the color blind, and safe for this
  mimicked "photocopying".  A service like https://colorbrewer2.org/
  may guide your selection.

  Keep a backup of the .pdf to be processed.  Though the script may
  report problems while processing the data (or even crash), it /is
  not/ a PDF validator such as e.g., veraPDF.[fn:3]
  
* Batch Conversion

  To process multiple =.pdf=, a for-loop in your shell could follow
  the pattern of

  #+begin_src shell
    for file in *.pdf
    do
        echo "$file"
        bash ./pdf_rewrite.sh -r "$file"
    done    
  #+end_src

  This equally provides you a simple progress report, too.


* Test case A

  The scripts' efficiency is tested in a Linux Xubuntu 18.04.3 LTS
  installation including ghostscript (version 9.26) on a review
  article by Kletskov /et al./[fn:4]  This was published by Thieme
  Verlag Stuttgart, Germany, as open access article under the terms of
  Creative Commons Attributions License, and is stored in its original
  form as file =Kletskov2020.pdf= in the repository.

  The original is worth 3.4 MB, features five color portraits of the
  authors of the publication, the the sparsely colored layout of the
  journal, line and gray-scale drawings.  The publication does not
  contain visible hyperlinks.

  The shell script is provided the executable bit.  Running the
  reprint instruction once decreases the file size of the .pdf file to
  2.3 MB, corresponding to a saving of 1.1 MB (about 32% of the
  original file size).

  Departing from the file already reprinted (retaining the color
  information) yields the gray-scale =output.pdf= of 677 kB with an
  additional saving of 0.4 MB (about 12% of the original file size).

* Test case B

  For a local check, you may run the script on file
  =link_example.pdf=.  This contains a simple color image from
  [[http://www.texample.net]] with a hyperlink to the original =.tex=
  source file slightly adapted here, =link_example.tex=, suitable for
  a compilation with =pdfLaTeX=.  The frame around the url in the .pdf
  is one (the default) option to indicate an URL which /some/ pdf
  readers display, but not necessary relay if the document is print.

  For a scientific publication containing cross- and hyperlinks, see
  Elgrishi /et al./ in their Open Access publication about
  Cyclovoltammetry (/J. Chem. Educ./ **2018**, /95/, 197--206; doi
  [[https://doi.org/10.1021/acs.jchemed.7b00361][10.1021/acs.jchemed.7b00361]]).  Starting with a .pdf of 2.2 MB, the
  reprint in color yields a file of 1.7 MB, the reprint in gray scale a
  file of 1.2 MB.  Both conversions retain cross- and hyperlinks.


* Footnotes

[fn:4] "Isothiazoles in the Design and Synthesis of Biologically
Active Substances and Ligands for Metal Complexes", Kletskov, A. V.;
Bumagin, N. A.; Zubkov, F. I.; Grudini, D. G.; Potkin,
V. I. /Synthesis/, *2020*, /52/, 159--188, [[https://www.thieme-connect.de/products/ejournals/abstract/10.1055/s-0039-1690688][doi 10.1055/s-0039-1690688]].

[fn:3] https://openpreservation.org/tools/verapdf/

[fn:2] https://unix.stackexchange.com/questions/93959/how-to-convert-a-color-pdf-to-black-white

[fn:1]  https://tex.stackexchange.com/questions/18987/how-to-make-the-pdfs-produced-by-pdflatex-smaller?rq=1
